use HADdb;

insert into questionnaire(name,questions,version) values
("Common",'{"Q1": {"options": ["Yes","No","NA"],"question": "Loss of Consciousness"},"Q2": {"options": ["Yes","No","NA"],"question": "Sudden episode of loss of contact with the surroundings"},"Q3": {"options": ["Yes","No","NA"],"question": "Uncontrollable shaking of head, arms or legs"},"Q4": {"options": ["Yes","No","NA"],"question": "Abnormal speech"},"Q5": {"options": ["Yes","No","NA"],"question": "Facial paralysis with sideways deviation of the mouth"},"Q6": {"options": ["Yes","No","NA"],"question": "Weakness or Paralysis of arms or legs"},"Q7": {"options": ["Yes","No","NA"],"question": "Difficulty in walking"},"Q8": {"options": ["Yes","No","NA"],"question": "Any loss of sensation or any abnormal sensation in the face, arms and legs"},"Q9": {"options": ["Yes","No","NA"],"question": "Deterioration of memory within the last five years"},"Q10": {"options": ["Temporary, for a few hours","Permanent","No","NA"],"question": "Drooping of eyelids"},"Q11": {"options": ["Yes","No","NA"],"question": "Episodes of severe facial pain"},"Q12": {"options": ["Unilateral","Associated with flashes of light or circles","Associated with vomiting","No","NA"],"question": "Headache"},"Q13": {"options": ["Yes","No","NA"],"question": "Any recent change in behavior or personality"},"Q14": { "options": ["Yes","No","NA"],"question": "Slowness of movement"},"Q15": {"options": ["Yes","No","NA"],"question": "Tremor"}}',"1"),
("Stroke1",'{"Q1": {"options": ["Yes","No","NA"],"question": "Weakness or loss of sensation on one side of body with deviation of face to one side"},"Q2": {"options": ["Yes","No","NA"],"question": "Impaired consciousness"},"Q3": {"options": ["Yes, Slurred speech","Yes, Difficulty in speaking or understanding","No","NA"],"question": " Speech difficulty"},"Q4": {"options": ["Yes","No","NA"],"question": "Loss of balance or incoordination while walking"},"Q5": {"options": ["Yes","No","NA"],"question": "Dizziness"},"Q6": {"options": ["Yes","No","NA"],"question": "Swallowing problems"},"Q7": {"options": ["Yes","No","NA"],"question": "Double vision"},"Q8": {"options": ["Yes","No","NA"],"question": "Vision impairment"}}',"1"),
("Epilepsy1",'{"Q1": {"options": ["Yes","No","NA"],"question": "Did they pass urine or stool in his/her clothes during an episode"},"Q2": {"options": ["Yes","No","NA"],"question": "Did they ever injure themselves or have tongue bite during an episode"},"Q3": {"options": ["Yes","No","NA"],"question": " Was there frothing from mouth during an episode"},"Q4": {"options": ["Yes","No","NA"],"question": "Did they have such an episode while asleep"},"Q5": {"options": ["Yes","No","NA"],"question": "Was the patient completely unconscious during the episode"},"Q6": {"options": ["Yes","No","NA"],"question": "Has an episode ever occurred WITHOUT preceding emotional or mental stress"},"Q7": {"options": ["Yes","No","NA"],"question": "Unprovoked stereotyped motor or sensory events, involving only one part of the body, with or withoutimpaired awareness of surroundings"},"Q8": {"options": ["Yes","No","NA"],"question": "patient had more than 1 unprovoked seizure 24 hours apart"},"Q9": {"options": ["Yes","No","NA"],"question": "Fever"},"Q10": {"options": [],"question": "Age"}}',"1"),
("Apx4",'{"Q1": {"options": ["Yes","No","NA"],"question": "Brief events (<few secs)"},"Q2": {"options": ["Yes","No","NA"],"question": "Blinking/staring"},"Q3": {"options": ["Yes","No","NA"],"question": "Multiple per day"},"Q4": {"options": ["Yes","No","NA"],"question": "Precipitated at bedside by hyperventilation"},"Q5": {"options": ["Yes","No","NA"],"question": "No developmental delay/regression"},"Q6": {"options": ["Yes","No","NA"],"question": "Onset after 3 years"}}',"1"),
("Apx5",'{"Q1": {"options": ["Yes","No","NA"],"question": "Generalized convulsive"},"Q2": {"options": ["Yes","No","NA"],"question": "Single episode"},"Q3": {"options": ["Yes","No","NA"],"question": "Lasts <5 minutes"},"Q4": {"options": ["Yes","No","NA"],"question": "No post ictal weakness"},"Q5": {"options": ["Yes","No","NA"],"question": " No developmental delay/regression"},"Q6": {"options": ["Yes","No","NA"],"question": "Regains consciousness completely within 5 min"},"Q7": {"options": [],"question": "Age"}}',"1");

insert into roles(name) values ("PRIMARY_DOCTOR"),("SECONDARY_SPECIALIST"),("TERTIARY_SPECIALIST"),("ADMIN");