import React from "react";
import { useSelector } from "react-redux";

import { ReferedListView } from "../views/ReferedListView";

export const ReferedContainer = () => {
    //const authState = useSelector(state => state.AuthReducer);
    const appiData = [
        {
            "id": 1,
            "patient": {
                "id": 1,
                "abhaId": "1234567890",
                "firstName": "shanthu",
                "lastName": "ressy",
                "dob": "2022-05-11",
                "age": 0,
                "gender": "Male",
                "education": "gyuasdfyu",
                "occupation": "hjgfss",
                "language": "fty",
                "socioEconomicStatus": "Above Poverty line",
                "address": "sdaf",
                "district": "adfs",
                "pincode": "574433",
                "phoneNo": "9876543210",
                "careGiverName": "madhav",
                "relationshipWithPatient": "friend",
                "bloodGroup": "B+"
            },
            "doctor": {
                "id": 1,
                "fname": "anvitha",
                "lname": "reddy",
                "password": "1234567890",
                "gender": "Male",
                "role": "Primary Doctor",
                "email": "anvitha@gmail.com",
                "hospitalName": "ecity",
                "contactNumber": "+919876543210",
                "hospital": {
                    "id": 1,
                    "name": "ecity",
                    "city": "vijayawada",
                    "state": "Andhra Pradesh",
                    "district": "prakasham",
                    "type": "Primary Health Centre",
                    "email": "ecity@gmail.com",
                    "pincode": "520007",
                    "contactNumber": "1234567890"
                }
            },
            "consultationDate": "2022-05-06",
            "complaint": "edfsa",
            "examination": "hg",
            "illnessSummary": "yuft",
            "diagnosisType": "Provisional",
            "icdDescription": "fghv",
            "icd10Code": "v68987",
            "improvementStatus": "Condition Worsened",
            "medicines": [
                {
                    "id": 1,
                    "medicineName": "gukjnb",
                    "dosage": "hgvj",
                    "dosingTime": "guih",
                    "duration": "gvhjbk"
                }
            ],
            "responses": [],
            "treatmentInstructions": "fgh",
            "remarks": "afd",
            "referedHospitalType": "Tertiary Health Centre",
            "referedHospitalId": 4,
            "referedHospital": "4. appolo, jhasf, 566567",
            "followUpDate": null,
            "moveToIp": false,
            "reviewSos": false,
            "suggestedDiagnosis": ""
        },
        {
            "id": 2,
            "patient": {
                "id": 1,
                "abhaId": "1234567890",
                "firstName": "shanthu",
                "lastName": "ressy",
                "dob": "2022-05-11",
                "age": 0,
                "gender": "Male",
                "education": "gyuasdfyu",
                "occupation": "hjgfss",
                "language": "fty",
                "socioEconomicStatus": "Above Poverty line",
                "address": "sdaf",
                "district": "adfs",
                "pincode": "574433",
                "phoneNo": "9876543210",
                "careGiverName": "madhav",
                "relationshipWithPatient": "friend",
                "bloodGroup": "B+"
            },
            "doctor": {
                "id": 1,
                "fname": "anvitha",
                "lname": "reddy",
                "password": "1234567890",
                "gender": "Male",
                "role": "Primary Doctor",
                "email": "anvitha@gmail.com",
                "hospitalName": "ecity",
                "contactNumber": "+919876543210",
                "hospital": {
                    "id": 1,
                    "name": "ecity",
                    "city": "vijayawada",
                    "state": "Andhra Pradesh",
                    "district": "prakasham",
                    "type": "Primary Health Centre",
                    "email": "ecity@gmail.com",
                    "pincode": "520007",
                    "contactNumber": "1234567890"
                }
            },
            "consultationDate": "2022-05-06",
            "complaint": "edfsa",
            "examination": "hg",
            "illnessSummary": "yuft",
            "diagnosisType": "Provisional",
            "icdDescription": "fghv",
            "icd10Code": "v68987",
            "improvementStatus": "Condition Worsened",
            "medicines": [
                {
                    "id": 2,
                    "medicineName": "gukjnb",
                    "dosage": "hgvj",
                    "dosingTime": "guih",
                    "duration": "gvhjbk"
                }
            ],
            "responses": [],
            "treatmentInstructions": "fgh",
            "remarks": "afd",
            "referedHospitalType": "Secondary Health Centre",
            "referedHospitalId": 3,
            "referedHospital": "3. applo, iuhasf, 876782",
            "followUpDate": null,
            "moveToIp": false,
            "reviewSos": false,
            "suggestedDiagnosis": ""
        },
        {
            "id": 3,
            "patient": {
                "id": 1,
                "abhaId": "1234567890",
                "firstName": "shanthu",
                "lastName": "ressy",
                "dob": "2022-05-11",
                "age": 0,
                "gender": "Male",
                "education": "gyuasdfyu",
                "occupation": "hjgfss",
                "language": "fty",
                "socioEconomicStatus": "Above Poverty line",
                "address": "sdaf",
                "district": "adfs",
                "pincode": "574433",
                "phoneNo": "9876543210",
                "careGiverName": "madhav",
                "relationshipWithPatient": "friend",
                "bloodGroup": "B+"
            },
            "doctor": {
                "id": 1,
                "fname": "anvitha",
                "lname": "reddy",
                "password": "1234567890",
                "gender": "Male",
                "role": "Primary Doctor",
                "email": "anvitha@gmail.com",
                "hospitalName": "ecity",
                "contactNumber": "+919876543210",
                "hospital": {
                    "id": 1,
                    "name": "ecity",
                    "city": "vijayawada",
                    "state": "Andhra Pradesh",
                    "district": "prakasham",
                    "type": "Primary Health Centre",
                    "email": "ecity@gmail.com",
                    "pincode": "520007",
                    "contactNumber": "1234567890"
                }
            },
            "consultationDate": "2022-05-06",
            "complaint": "edfsa",
            "examination": "hg",
            "illnessSummary": "yuft",
            "diagnosisType": "Provisional",
            "icdDescription": "fghv",
            "icd10Code": "v68987",
            "improvementStatus": "Condition Worsened",
            "medicines": [
                {
                    "id": 3,
                    "medicineName": "gukjnb",
                    "dosage": "hgvj",
                    "dosingTime": "guih",
                    "duration": "gvhjbk"
                }
            ],
            "responses": [],
            "treatmentInstructions": "fgh",
            "remarks": "afd",
            "referedHospitalType": "Primary Health Centre",
            "referedHospitalId": 2,
            "referedHospital": "2. helloworld, mangalore, 560100",
            "followUpDate": null,
            "moveToIp": false,
            "reviewSos": false,
            "suggestedDiagnosis": ""
        },
        {
            "id": 4,
            "patient": {
                "id": 1,
                "abhaId": "1234567890",
                "firstName": "shanthu",
                "lastName": "ressy",
                "dob": "2022-05-11",
                "age": 0,
                "gender": "Male",
                "education": "gyuasdfyu",
                "occupation": "hjgfss",
                "language": "fty",
                "socioEconomicStatus": "Above Poverty line",
                "address": "sdaf",
                "district": "adfs",
                "pincode": "574433",
                "phoneNo": "9876543210",
                "careGiverName": "madhav",
                "relationshipWithPatient": "friend",
                "bloodGroup": "B+"
            },
            "doctor": {
                "id": 1,
                "fname": "anvitha",
                "lname": "reddy",
                "password": "1234567890",
                "gender": "Male",
                "role": "Primary Doctor",
                "email": "anvitha@gmail.com",
                "hospitalName": "ecity",
                "contactNumber": "+919876543210",
                "hospital": {
                    "id": 1,
                    "name": "ecity",
                    "city": "vijayawada",
                    "state": "Andhra Pradesh",
                    "district": "prakasham",
                    "type": "Primary Health Centre",
                    "email": "ecity@gmail.com",
                    "pincode": "520007",
                    "contactNumber": "1234567890"
                }
            },
            "consultationDate": "2022-05-06",
            "complaint": "edfsa",
            "examination": "hg",
            "illnessSummary": "yuft",
            "diagnosisType": "Provisional",
            "icdDescription": "fghv",
            "icd10Code": "v68987",
            "improvementStatus": "Condition Worsened",
            "medicines": [
                {
                    "id": 4,
                    "medicineName": "gukjnb",
                    "dosage": "hgvj",
                    "dosingTime": "guih",
                    "duration": "gvhjbk"
                }
            ],
            "responses": [],
            "treatmentInstructions": "fgh",
            "remarks": "afd",
            "referedHospitalType": "Secondary Health Centre",
            "referedHospitalId": 4,
            "referedHospital": "4. appolo, jhasf, 566567",
            "followUpDate": null,
            "moveToIp": false,
            "reviewSos": false,
            "suggestedDiagnosis": ""
        },
        {
            "id": 5,
            "patient": {
                "id": 1,
                "abhaId": "1234567890",
                "firstName": "shanthu",
                "lastName": "ressy",
                "dob": "2022-05-11",
                "age": 0,
                "gender": "Male",
                "education": "gyuasdfyu",
                "occupation": "hjgfss",
                "language": "fty",
                "socioEconomicStatus": "Above Poverty line",
                "address": "sdaf",
                "district": "adfs",
                "pincode": "574433",
                "phoneNo": "9876543210",
                "careGiverName": "madhav",
                "relationshipWithPatient": "friend",
                "bloodGroup": "B+"
            },
            "doctor": {
                "id": 1,
                "fname": "anvitha",
                "lname": "reddy",
                "password": "1234567890",
                "gender": "Male",
                "role": "Primary Doctor",
                "email": "anvitha@gmail.com",
                "hospitalName": "ecity",
                "contactNumber": "+919876543210",
                "hospital": {
                    "id": 1,
                    "name": "ecity",
                    "city": "vijayawada",
                    "state": "Andhra Pradesh",
                    "district": "prakasham",
                    "type": "Primary Health Centre",
                    "email": "ecity@gmail.com",
                    "pincode": "520007",
                    "contactNumber": "1234567890"
                }
            },
            "consultationDate": "2022-05-06",
            "complaint": "afdaghv",
            "examination": "gugy",
            "illnessSummary": "gvyhj",
            "diagnosisType": "Provisional",
            "icdDescription": "gvhj",
            "icd10Code": "asdf",
            "improvementStatus": "Condition Worsened",
            "medicines": [
                {
                    "id": 5,
                    "medicineName": "afd",
                    "dosage": "dasf",
                    "dosingTime": "adf",
                    "duration": "afd"
                }
            ],
            "responses": [],
            "treatmentInstructions": "adf",
            "remarks": "af",
            "referedHospitalType": "",
            "referedHospitalId": 0,
            "referedHospital": "",
            "followUpDate": null,
            "moveToIp": true,
            "reviewSos": false,
            "suggestedDiagnosis": ""
        },
        {
            "id": 6,
            "patient": {
                "id": 1,
                "abhaId": "1234567890",
                "firstName": "shanthu",
                "lastName": "ressy",
                "dob": "2022-05-11",
                "age": 0,
                "gender": "Male",
                "education": "gyuasdfyu",
                "occupation": "hjgfss",
                "language": "fty",
                "socioEconomicStatus": "Above Poverty line",
                "address": "sdaf",
                "district": "adfs",
                "pincode": "574433",
                "phoneNo": "9876543210",
                "careGiverName": "madhav",
                "relationshipWithPatient": "friend",
                "bloodGroup": "B+"
            },
            "doctor": {
                "id": 1,
                "fname": "anvitha",
                "lname": "reddy",
                "password": "1234567890",
                "gender": "Male",
                "role": "Primary Doctor",
                "email": "anvitha@gmail.com",
                "hospitalName": "ecity",
                "contactNumber": "+919876543210",
                "hospital": {
                    "id": 1,
                    "name": "ecity",
                    "city": "vijayawada",
                    "state": "Andhra Pradesh",
                    "district": "prakasham",
                    "type": "Primary Health Centre",
                    "email": "ecity@gmail.com",
                    "pincode": "520007",
                    "contactNumber": "1234567890"
                }
            },
            "consultationDate": "2022-05-06",
            "complaint": "afdaghv",
            "examination": "gugy",
            "illnessSummary": "gvyhj",
            "diagnosisType": "Provisional",
            "icdDescription": "gvhj",
            "icd10Code": "asdf",
            "improvementStatus": "Condition Worsened",
            "medicines": [
                {
                    "id": 6,
                    "medicineName": "afd",
                    "dosage": "dasf",
                    "dosingTime": "adf",
                    "duration": "afd"
                }
            ],
            "responses": [],
            "treatmentInstructions": "adf",
            "remarks": "af",
            "referedHospitalType": "",
            "referedHospitalId": 0,
            "referedHospital": "",
            "followUpDate": null,
            "moveToIp": false,
            "reviewSos": true,
            "suggestedDiagnosis": ""
        },
        {
            "id": 7,
            "patient": {
                "id": 1,
                "abhaId": "1234567890",
                "firstName": "shanthu",
                "lastName": "ressy",
                "dob": "2022-05-11",
                "age": 0,
                "gender": "Male",
                "education": "gyuasdfyu",
                "occupation": "hjgfss",
                "language": "fty",
                "socioEconomicStatus": "Above Poverty line",
                "address": "sdaf",
                "district": "adfs",
                "pincode": "574433",
                "phoneNo": "9876543210",
                "careGiverName": "madhav",
                "relationshipWithPatient": "friend",
                "bloodGroup": "B+"
            },
            "doctor": {
                "id": 1,
                "fname": "anvitha",
                "lname": "reddy",
                "password": "1234567890",
                "gender": "Male",
                "role": "Primary Doctor",
                "email": "anvitha@gmail.com",
                "hospitalName": "ecity",
                "contactNumber": "+919876543210",
                "hospital": {
                    "id": 1,
                    "name": "ecity",
                    "city": "vijayawada",
                    "state": "Andhra Pradesh",
                    "district": "prakasham",
                    "type": "Primary Health Centre",
                    "email": "ecity@gmail.com",
                    "pincode": "520007",
                    "contactNumber": "1234567890"
                }
            },
            "consultationDate": "2022-05-06",
            "complaint": "afdaghv",
            "examination": "gugy",
            "illnessSummary": "gvyhj",
            "diagnosisType": "Provisional",
            "icdDescription": "gvhj",
            "icd10Code": "asdf",
            "improvementStatus": "Condition Worsened",
            "medicines": [
                {
                    "id": 7,
                    "medicineName": "afd",
                    "dosage": "dasf",
                    "dosingTime": "adf",
                    "duration": "afd"
                }
            ],
            "responses": [],
            "treatmentInstructions": "adf",
            "remarks": "af",
            "referedHospitalType": "",
            "referedHospitalId": 0,
            "referedHospital": "",
            "followUpDate": "2022-05-31",
            "moveToIp": false,
            "reviewSos": false,
            "suggestedDiagnosis": ""
        },
        {
            "id": 8,
            "patient": {
                "id": 1,
                "abhaId": "1234567890",
                "firstName": "shanthu",
                "lastName": "ressy",
                "dob": "2022-05-11",
                "age": 0,
                "gender": "Male",
                "education": "gyuasdfyu",
                "occupation": "hjgfss",
                "language": "fty",
                "socioEconomicStatus": "Above Poverty line",
                "address": "sdaf",
                "district": "adfs",
                "pincode": "574433",
                "phoneNo": "9876543210",
                "careGiverName": "madhav",
                "relationshipWithPatient": "friend",
                "bloodGroup": "B+"
            },
            "doctor": {
                "id": 1,
                "fname": "anvitha",
                "lname": "reddy",
                "password": "1234567890",
                "gender": "Male",
                "role": "Primary Doctor",
                "email": "anvitha@gmail.com",
                "hospitalName": "ecity",
                "contactNumber": "+919876543210",
                "hospital": {
                    "id": 1,
                    "name": "ecity",
                    "city": "vijayawada",
                    "state": "Andhra Pradesh",
                    "district": "prakasham",
                    "type": "Primary Health Centre",
                    "email": "ecity@gmail.com",
                    "pincode": "520007",
                    "contactNumber": "1234567890"
                }
            },
            "consultationDate": "2022-05-06",
            "complaint": "afdaghv",
            "examination": "gugy",
            "illnessSummary": "gvyhj",
            "diagnosisType": "Provisional",
            "icdDescription": "gvhj",
            "icd10Code": "asdf",
            "improvementStatus": "Condition Worsened",
            "medicines": [
                {
                    "id": 8,
                    "medicineName": "afd",
                    "dosage": "dasf",
                    "dosingTime": "adf",
                    "duration": "afd"
                }
            ],
            "responses": [],
            "treatmentInstructions": "adf",
            "remarks": "af",
            "referedHospitalType": "Secondary Health Centre",
            "referedHospitalId": 3,
            "referedHospital": "3. applo, iuhasf, 876782",
            "followUpDate": null,
            "moveToIp": false,
            "reviewSos": false,
            "suggestedDiagnosis": ""
        },
        {
            "id": 9,
            "patient": {
                "id": 1,
                "abhaId": "1234567890",
                "firstName": "shanthu",
                "lastName": "ressy",
                "dob": "2022-05-11",
                "age": 0,
                "gender": "Male",
                "education": "gyuasdfyu",
                "occupation": "hjgfss",
                "language": "fty",
                "socioEconomicStatus": "Above Poverty line",
                "address": "sdaf",
                "district": "adfs",
                "pincode": "574433",
                "phoneNo": "9876543210",
                "careGiverName": "madhav",
                "relationshipWithPatient": "friend",
                "bloodGroup": "B+"
            },
            "doctor": {
                "id": 1,
                "fname": "anvitha",
                "lname": "reddy",
                "password": "1234567890",
                "gender": "Male",
                "role": "Primary Doctor",
                "email": "anvitha@gmail.com",
                "hospitalName": "ecity",
                "contactNumber": "+919876543210",
                "hospital": {
                    "id": 1,
                    "name": "ecity",
                    "city": "vijayawada",
                    "state": "Andhra Pradesh",
                    "district": "prakasham",
                    "type": "Primary Health Centre",
                    "email": "ecity@gmail.com",
                    "pincode": "520007",
                    "contactNumber": "1234567890"
                }
            },
            "consultationDate": "2022-05-06",
            "complaint": "afdaghv",
            "examination": "gugy",
            "illnessSummary": "gvyhj",
            "diagnosisType": "Provisional",
            "icdDescription": "gvhj",
            "icd10Code": "asdf",
            "improvementStatus": "Condition Worsened",
            "medicines": [
                {
                    "id": 9,
                    "medicineName": "afd",
                    "dosage": "dasf",
                    "dosingTime": "adf",
                    "duration": "afd"
                }
            ],
            "responses": [],
            "treatmentInstructions": "adf",
            "remarks": "af",
            "referedHospitalType": "Secondary Health Centre",
            "referedHospitalId": 3,
            "referedHospital": "3. applo, iuhasf, 876782",
            "followUpDate": null,
            "moveToIp": false,
            "reviewSos": true,
            "suggestedDiagnosis": ""
        },
        {
            "id": 10,
            "patient": {
                "id": 1,
                "abhaId": "1234567890",
                "firstName": "shanthu",
                "lastName": "ressy",
                "dob": "2022-05-11",
                "age": 0,
                "gender": "Male",
                "education": "gyuasdfyu",
                "occupation": "hjgfss",
                "language": "fty",
                "socioEconomicStatus": "Above Poverty line",
                "address": "sdaf",
                "district": "adfs",
                "pincode": "574433",
                "phoneNo": "9876543210",
                "careGiverName": "madhav",
                "relationshipWithPatient": "friend",
                "bloodGroup": "B+"
            },
            "doctor": {
                "id": 1,
                "fname": "anvitha",
                "lname": "reddy",
                "password": "1234567890",
                "gender": "Male",
                "role": "Primary Doctor",
                "email": "anvitha@gmail.com",
                "hospitalName": "ecity",
                "contactNumber": "+919876543210",
                "hospital": {
                    "id": 1,
                    "name": "ecity",
                    "city": "vijayawada",
                    "state": "Andhra Pradesh",
                    "district": "prakasham",
                    "type": "Primary Health Centre",
                    "email": "ecity@gmail.com",
                    "pincode": "520007",
                    "contactNumber": "1234567890"
                }
            },
            "consultationDate": "2022-05-06",
            "complaint": "afdaghv",
            "examination": "gugy",
            "illnessSummary": "gvyhj",
            "diagnosisType": "Provisional",
            "icdDescription": "gvhj",
            "icd10Code": "asdf",
            "improvementStatus": "Condition Worsened",
            "medicines": [
                {
                    "id": 10,
                    "medicineName": "afd",
                    "dosage": "dasf",
                    "dosingTime": "adf",
                    "duration": "afd"
                }
            ],
            "responses": [],
            "treatmentInstructions": "adf",
            "remarks": "af",
            "referedHospitalType": "Secondary Health Centre",
            "referedHospitalId": 3,
            "referedHospital": "3. applo, iuhasf, 876782",
            "followUpDate": null,
            "moveToIp": true,
            "reviewSos": false,
            "suggestedDiagnosis": ""
        }
    ]
   return  <ReferedListView apiData={appiData} ></ReferedListView>
}